### ISSUE TITLE
Fatal error while running mlflow server command

### ISSUE THREAD

**Issue by dpapadop** [osin-vladimir/pydata_ehv_mlflow#3]
I am getting this error ```
Fatal error in launcher: Unable to create process using '"d:\bld\mlflow_1572494804636\_h_env\python.exe"  "C:\Users\padi7003\AppData\Local\Continuum\miniconda3\envs\mlflow-tut
orial\Scripts\mlflow.exe" server --backend-store-uri=sqlite:///C:\\projects\\personal\\mlflow_tutorial\\backend\\mlflow_ui_data.db --default-artifact-root=file:///C:\\projects
\\personal\\mlflow_tutorial\\artifact_store\\'
``` after running ```
mlflow server --backend-store-uri="sqlite:///C:\\projects\\personal\\mlflow_tutorial\\backend\\mlflow_ui_data.db" --default-ar
tifact-root="file:///C:\\projects\\personal\\mlflow_tutorial\\artifact_store\\"
```  from the terminal inside Jupyter Lab Interface. 

Any ideas what might cause it ?

**Comment by osin-vladimir** [comment]
@dpapadop  Please check your antivirus. My one deleted python.exe from conda environment when I tried to launch first time. Hope it helps.

**Comment by osin-vladimir** [comment]
@dpapadop closing for now. Feel free to re-open if not yet solved.
